export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const LOADING_PROFILE = 'LOADING_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR';